import { z } from 'zod';

// --- Primitives ---
export const ObjectIdSchema = z.string().regex(/^[0-9a-fA-F]{24}$/, "Invalid MongoDB ObjectId");
// For UUIDs generated by the app (if mixed with Mongo ObjectIds, handle carefully. 
// Current app uses uuidv4 or crypto.randomUUID mostly)
export const IdSchema = z.union([z.string().uuid(), ObjectIdSchema, z.string().min(1)]);

// --- User Schema ---
export const UserSchema = z.object({
    username: z.string().min(3, "Username must be at least 3 characters"),
    pin: z.string().min(4, "PIN must be at least 4 characters"), // Hashed in DB, but input validation needed
    email: z.string().email().optional().or(z.literal('')),
    // Internal fields usually not exposed to frontend
    totpSecret: z.string().optional(),
    refreshToken: z.string().optional(),
    currency: z.string().default('INR'),
});

// Safe User Projections (DTOs)
export const UserProfileSchema = UserSchema.pick({
    username: true,
    email: true
}).extend({
    id: IdSchema
});

// --- Transaction Schema ---
export const TransactionTypeSchema = z.enum(['income', 'expense']);
export const FrequencySchema = z.enum(['daily', 'weekly', 'monthly', 'yearly']);

export const TransactionSchema = z.object({
    id: IdSchema,
    userId: z.string(), // In a real app with ObjectId, this might be ObjectIdSchema
    amount: z.number().positive("Amount must be positive"),
    type: TransactionTypeSchema,
    category: z.string().min(1, "Category is required"),
    description: z.string().min(1, "Description is required"),
    date: z.string().datetime().or(z.date().transform(d => d.toISOString())), // ISO String preferred
});

export const CreateTransactionSchema = TransactionSchema.omit({
    id: true,
    userId: true // Inferred from session
});

// --- Budget Schema ---
// Aligning with the somewhat complex structure in original models.ts
export const BudgetEntrySchema = z.object({
    id: IdSchema,
    name: z.string().min(1),
    amount: z.number().positive(),
    type: TransactionTypeSchema,
    date: z.string()
});

export const BudgetSchema = z.object({
    userId: z.string(),
    fixedExpenses: z.array(z.object({
        id: IdSchema,
        name: z.string(),
        amount: z.number().nonnegative()
    })),
    allocations: z.array(z.object({
        id: IdSchema,
        name: z.string(),
        percentage: z.number().min(0).max(100),
        cap: z.number().positive().optional(), // New: Hard limit for better budgeting
        color: z.string()
    })),
    entries: z.array(BudgetEntrySchema).optional()
});

// --- Recurring Rules Schema ---
export const RecurringRuleSchema = z.object({
    id: IdSchema,
    userId: z.string(),
    type: TransactionTypeSchema,
    category: z.string(),
    description: z.string(),
    amount: z.number().positive(),
    frequency: FrequencySchema,
    startDate: z.string().datetime(),
    nextDueDate: z.string().datetime(),
    active: z.boolean().default(true),
    lastProcessed: z.string().datetime().optional()
});

// --- API/Action Input Schemas ---
export const LoginSchema = z.object({
    username: z.string(),
    pin: z.string()
});

export const RegisterSchema = z.object({
    username: z.string().min(3),
    pin: z.string().min(4),
    email: z.string().email().optional()
});
